### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'messaging')

### ISSUE THREAD

**Issue by PMLS3** [becem-gharbi/nuxt-fcm#1]
I am using :
@bg-dev/nuxt-fcm": "^0.2.5"
"nuxt": "^3.5.1",

And keep on getting the error in the title: 

If I inspect further it seems that my $fcm is not registration, I have followed the steps as per docs, not sure what I am missing and hope someone can assist: 

import { useNuxtApp } from "/_nuxt/node_modules/nuxt/dist/app/index.js?v=beecf9d0";
import { getToken as _getToken } from "/_nuxt/node_modules/firebase/messaging/dist/esm/index.esm.js?v=beecf9d0";
import { onMessage as _onMessage } from "/_nuxt/node_modules/firebase/messaging/dist/esm/index.esm.js?v=beecf9d0";
export default function() {
  const { $fcm } = useNuxtApp();
  async function getToken() {
    return _getToken($fcm.messaging).catch(() => "");
  }
  function onMessage(cb) {
    _onMessage($fcm.messaging, cb);
  }
  return { getToken, onMessage };
}

**Comment by becem-gharbi** [comment]
Thanks for your feedback, 
Indeed, messaging is undefined on server side. This is because it's provided only client side on firebase [initialization](https://github.com/becem-gharbi/nuxt-fcm/blob/main/src/runtime/firebase.client.ts). I have added a note on **Listen to messages** section. Thus you need to make sure to call `useFcm` composable on `ClientOnly` component or check the `process.client` first. Perhaps, the module should handle this case internally.

**Comment by becem-gharbi** [comment]
Just pushed a patch [v0.2.6](https://github.com/becem-gharbi/nuxt-fcm/releases/tag/v0.2.6).
